title: Lernae
theme: dark
color: slate
cardBlur: md
background:
  image: /images/background.jpg
  opacity: 85
headerStyle: clean
favicon: /images/lernae/favicon-32.png
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google
layout:
  Bibliotecas:
    style: row
    columns: 2
  Automatización:
    style: row
    columns: 3
  Infraestructura:
    style: row
    columns: 2
