title: Lernae
theme: dark
color: slate
cardBlur: md
background:
  image: /images/background.jpg
  opacity: 85
headerStyle: clean
favicon: /images/lernae/favicon-32.png
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google
layout:
  Medios y Entretenimiento:
    style: row
    columns: 2
  Automatización (Libros y Novelas):
    style: row
    columns: 3
  Ecosistema y Conectividad:
    style: row
    columns: 2
