- greeting:
    text_size: 2xl
    text: "Lernae"

- openmeteo:
    label: Santiago
    latitude: -33.4569
    longitude: -70.6483
    timezone: America/Santiago
    units: metric

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: medium

- resources:
    cpu: true
    memory: true
    disk: /app/config
